# Set theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Name of Site
title: Allie Bergmann
description: Data Scientist, Stock/Crypto Algorithmic Trading Enthusiast

# Your name to show in the footer
author: Allison Bergmann

# Google Analytics
google_analytics: G-KM29CNVYG4

# Contact/Social Media
social-network-links:
  email: "11arbergmann@gmail.com"
  linkedin: arbergmann
  github: arbergmann
