# Set theme
theme: jekyll-theme-minimal

# Name of Site
title: Allie Bergmann
subtitle: Data Scientist, Stock/Crypto Algorithmic Trading Enthusiast

# Your name to show in the footer
author: Allison Bergmann


google_analytics: "216084922"
